print('Tabela Brasileirão')
print('================================================================================================================================================================')
le = ( 'Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro', 'Flamengo', 'Vasco', 'Chapecoense', 'Atlético', 'Botafogo', 'Atlético-PR', 'Bahia', 'São Paulo', 'Fluminense', 'Sport Recife', 'EC Vitória', 'Coritiba', 'Avaí', 'Ponte Preta', 'Atlético-GO')
print('A Tabela de o Brasileirão segue a seguinte ordem de classificação :\n{}'.format(le))
print('================================================================================================================================================================')
print('Os 5 primeiros classificados do Brasileirão em ordem de classificação :\n{}'.format(le[0:5]))
print('================================================================================================================================================================')
print('Os 4 ultimos classificados do Brasileirão em ordem de classificação :\n{}'.format(le[-4:]))
print('================================================================================================================================================================')
print(f'Os times do Brasileirão em ordem alfabetica :\n {sorted(le)} ')
print('================================================================================================================================================================')
cp = le.index('Chapecoense')
print('A posição que se encontra o time da "Chapecoense" na classificados do Brasileirão é : {}ª'.format(cp + 1))
print('================================================================================================================================================================')
